# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/last/CLionProjects/EmpresaAerea

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/last/CLionProjects/EmpresaAerea

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/last/CLionProjects/EmpresaAerea/CMakeFiles /home/last/CLionProjects/EmpresaAerea/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/last/CLionProjects/EmpresaAerea/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AeroTracker

# Build rule for target.
AeroTracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AeroTracker
.PHONY : AeroTracker

# fast build rule for target.
AeroTracker/fast:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/build
.PHONY : AeroTracker/fast

core/Aeronave/Aeronave.o: core/Aeronave/Aeronave.c.o

.PHONY : core/Aeronave/Aeronave.o

# target to build an object file
core/Aeronave/Aeronave.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeronave/Aeronave.c.o
.PHONY : core/Aeronave/Aeronave.c.o

core/Aeronave/Aeronave.i: core/Aeronave/Aeronave.c.i

.PHONY : core/Aeronave/Aeronave.i

# target to preprocess a source file
core/Aeronave/Aeronave.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeronave/Aeronave.c.i
.PHONY : core/Aeronave/Aeronave.c.i

core/Aeronave/Aeronave.s: core/Aeronave/Aeronave.c.s

.PHONY : core/Aeronave/Aeronave.s

# target to generate assembly for a file
core/Aeronave/Aeronave.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeronave/Aeronave.c.s
.PHONY : core/Aeronave/Aeronave.c.s

core/Aeronave/Comparator.o: core/Aeronave/Comparator.c.o

.PHONY : core/Aeronave/Comparator.o

# target to build an object file
core/Aeronave/Comparator.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeronave/Comparator.c.o
.PHONY : core/Aeronave/Comparator.c.o

core/Aeronave/Comparator.i: core/Aeronave/Comparator.c.i

.PHONY : core/Aeronave/Comparator.i

# target to preprocess a source file
core/Aeronave/Comparator.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeronave/Comparator.c.i
.PHONY : core/Aeronave/Comparator.c.i

core/Aeronave/Comparator.s: core/Aeronave/Comparator.c.s

.PHONY : core/Aeronave/Comparator.s

# target to generate assembly for a file
core/Aeronave/Comparator.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeronave/Comparator.c.s
.PHONY : core/Aeronave/Comparator.c.s

core/Aeroporto/Aeroporto.o: core/Aeroporto/Aeroporto.c.o

.PHONY : core/Aeroporto/Aeroporto.o

# target to build an object file
core/Aeroporto/Aeroporto.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeroporto/Aeroporto.c.o
.PHONY : core/Aeroporto/Aeroporto.c.o

core/Aeroporto/Aeroporto.i: core/Aeroporto/Aeroporto.c.i

.PHONY : core/Aeroporto/Aeroporto.i

# target to preprocess a source file
core/Aeroporto/Aeroporto.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeroporto/Aeroporto.c.i
.PHONY : core/Aeroporto/Aeroporto.c.i

core/Aeroporto/Aeroporto.s: core/Aeroporto/Aeroporto.c.s

.PHONY : core/Aeroporto/Aeroporto.s

# target to generate assembly for a file
core/Aeroporto/Aeroporto.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeroporto/Aeroporto.c.s
.PHONY : core/Aeroporto/Aeroporto.c.s

core/Aeroporto/Comparator.o: core/Aeroporto/Comparator.c.o

.PHONY : core/Aeroporto/Comparator.o

# target to build an object file
core/Aeroporto/Comparator.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeroporto/Comparator.c.o
.PHONY : core/Aeroporto/Comparator.c.o

core/Aeroporto/Comparator.i: core/Aeroporto/Comparator.c.i

.PHONY : core/Aeroporto/Comparator.i

# target to preprocess a source file
core/Aeroporto/Comparator.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeroporto/Comparator.c.i
.PHONY : core/Aeroporto/Comparator.c.i

core/Aeroporto/Comparator.s: core/Aeroporto/Comparator.c.s

.PHONY : core/Aeroporto/Comparator.s

# target to generate assembly for a file
core/Aeroporto/Comparator.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Aeroporto/Comparator.c.s
.PHONY : core/Aeroporto/Comparator.c.s

core/Cliente/Cliente.o: core/Cliente/Cliente.c.o

.PHONY : core/Cliente/Cliente.o

# target to build an object file
core/Cliente/Cliente.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Cliente/Cliente.c.o
.PHONY : core/Cliente/Cliente.c.o

core/Cliente/Cliente.i: core/Cliente/Cliente.c.i

.PHONY : core/Cliente/Cliente.i

# target to preprocess a source file
core/Cliente/Cliente.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Cliente/Cliente.c.i
.PHONY : core/Cliente/Cliente.c.i

core/Cliente/Cliente.s: core/Cliente/Cliente.c.s

.PHONY : core/Cliente/Cliente.s

# target to generate assembly for a file
core/Cliente/Cliente.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Cliente/Cliente.c.s
.PHONY : core/Cliente/Cliente.c.s

core/Cliente/Comparator.o: core/Cliente/Comparator.c.o

.PHONY : core/Cliente/Comparator.o

# target to build an object file
core/Cliente/Comparator.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Cliente/Comparator.c.o
.PHONY : core/Cliente/Comparator.c.o

core/Cliente/Comparator.i: core/Cliente/Comparator.c.i

.PHONY : core/Cliente/Comparator.i

# target to preprocess a source file
core/Cliente/Comparator.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Cliente/Comparator.c.i
.PHONY : core/Cliente/Comparator.c.i

core/Cliente/Comparator.s: core/Cliente/Comparator.c.s

.PHONY : core/Cliente/Comparator.s

# target to generate assembly for a file
core/Cliente/Comparator.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Cliente/Comparator.c.s
.PHONY : core/Cliente/Comparator.c.s

core/List/Operations/List.o: core/List/Operations/List.c.o

.PHONY : core/List/Operations/List.o

# target to build an object file
core/List/Operations/List.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/List/Operations/List.c.o
.PHONY : core/List/Operations/List.c.o

core/List/Operations/List.i: core/List/Operations/List.c.i

.PHONY : core/List/Operations/List.i

# target to preprocess a source file
core/List/Operations/List.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/List/Operations/List.c.i
.PHONY : core/List/Operations/List.c.i

core/List/Operations/List.s: core/List/Operations/List.c.s

.PHONY : core/List/Operations/List.s

# target to generate assembly for a file
core/List/Operations/List.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/List/Operations/List.c.s
.PHONY : core/List/Operations/List.c.s

core/List/Sort/mergeSort.o: core/List/Sort/mergeSort.c.o

.PHONY : core/List/Sort/mergeSort.o

# target to build an object file
core/List/Sort/mergeSort.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/List/Sort/mergeSort.c.o
.PHONY : core/List/Sort/mergeSort.c.o

core/List/Sort/mergeSort.i: core/List/Sort/mergeSort.c.i

.PHONY : core/List/Sort/mergeSort.i

# target to preprocess a source file
core/List/Sort/mergeSort.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/List/Sort/mergeSort.c.i
.PHONY : core/List/Sort/mergeSort.c.i

core/List/Sort/mergeSort.s: core/List/Sort/mergeSort.c.s

.PHONY : core/List/Sort/mergeSort.s

# target to generate assembly for a file
core/List/Sort/mergeSort.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/List/Sort/mergeSort.c.s
.PHONY : core/List/Sort/mergeSort.c.s

core/Voo/Comparator.o: core/Voo/Comparator.c.o

.PHONY : core/Voo/Comparator.o

# target to build an object file
core/Voo/Comparator.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Voo/Comparator.c.o
.PHONY : core/Voo/Comparator.c.o

core/Voo/Comparator.i: core/Voo/Comparator.c.i

.PHONY : core/Voo/Comparator.i

# target to preprocess a source file
core/Voo/Comparator.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Voo/Comparator.c.i
.PHONY : core/Voo/Comparator.c.i

core/Voo/Comparator.s: core/Voo/Comparator.c.s

.PHONY : core/Voo/Comparator.s

# target to generate assembly for a file
core/Voo/Comparator.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Voo/Comparator.c.s
.PHONY : core/Voo/Comparator.c.s

core/Voo/VooInfo.o: core/Voo/VooInfo.c.o

.PHONY : core/Voo/VooInfo.o

# target to build an object file
core/Voo/VooInfo.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Voo/VooInfo.c.o
.PHONY : core/Voo/VooInfo.c.o

core/Voo/VooInfo.i: core/Voo/VooInfo.c.i

.PHONY : core/Voo/VooInfo.i

# target to preprocess a source file
core/Voo/VooInfo.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Voo/VooInfo.c.i
.PHONY : core/Voo/VooInfo.c.i

core/Voo/VooInfo.s: core/Voo/VooInfo.c.s

.PHONY : core/Voo/VooInfo.s

# target to generate assembly for a file
core/Voo/VooInfo.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/core/Voo/VooInfo.c.s
.PHONY : core/Voo/VooInfo.c.s

input/string.o: input/string.c.o

.PHONY : input/string.o

# target to build an object file
input/string.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/input/string.c.o
.PHONY : input/string.c.o

input/string.i: input/string.c.i

.PHONY : input/string.i

# target to preprocess a source file
input/string.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/input/string.c.i
.PHONY : input/string.c.i

input/string.s: input/string.c.s

.PHONY : input/string.s

# target to generate assembly for a file
input/string.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/input/string.c.s
.PHONY : input/string.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/main.c.s
.PHONY : main.c.s

ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.o: ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.o

ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.i: ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.i

ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.s: ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.c.s

ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.o: ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.o

ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.i: ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.i

ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.s: ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.c.s

ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.o: ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.o

ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.i: ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.i

ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.s: ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.c.s

ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.o: ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.o

ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.i: ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.i

ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.s: ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.c.s

ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.o: ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.o

ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.i: ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.i

ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.s: ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.c.s

ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.o: ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.o

ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.i: ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.i

ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.s: ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.c.s

ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.o: ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.o

ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.i: ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.i

ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.s: ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.c.s

ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.o: ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.o

ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.i: ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.i

ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.s: ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.c.s

ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.o: ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.o

ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.i: ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.i

ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.s: ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.c.s

ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.o: ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.o

ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.i: ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.i

ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.s: ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.c.s

ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.o: ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.o

ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.i: ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.i

ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.s: ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.c.s

ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.o: ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.o

ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.i: ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.i

ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.s: ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.c.s

ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.o: ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.o

ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.i: ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.i

ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.s: ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.c.s

ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.o: ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.o

ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.i: ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.i

ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.s: ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.c.s

ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.o: ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.o

.PHONY : ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.o

# target to build an object file
ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.o
.PHONY : ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.o

ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.i: ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.i

.PHONY : ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.i
.PHONY : ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.i

ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.s: ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.s

.PHONY : ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.s
.PHONY : ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.c.s

ui/Menu/Main/Cadastros/cadastrosMenuUI.o: ui/Menu/Main/Cadastros/cadastrosMenuUI.c.o

.PHONY : ui/Menu/Main/Cadastros/cadastrosMenuUI.o

# target to build an object file
ui/Menu/Main/Cadastros/cadastrosMenuUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/cadastrosMenuUI.c.o
.PHONY : ui/Menu/Main/Cadastros/cadastrosMenuUI.c.o

ui/Menu/Main/Cadastros/cadastrosMenuUI.i: ui/Menu/Main/Cadastros/cadastrosMenuUI.c.i

.PHONY : ui/Menu/Main/Cadastros/cadastrosMenuUI.i

# target to preprocess a source file
ui/Menu/Main/Cadastros/cadastrosMenuUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/cadastrosMenuUI.c.i
.PHONY : ui/Menu/Main/Cadastros/cadastrosMenuUI.c.i

ui/Menu/Main/Cadastros/cadastrosMenuUI.s: ui/Menu/Main/Cadastros/cadastrosMenuUI.c.s

.PHONY : ui/Menu/Main/Cadastros/cadastrosMenuUI.s

# target to generate assembly for a file
ui/Menu/Main/Cadastros/cadastrosMenuUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Cadastros/cadastrosMenuUI.c.s
.PHONY : ui/Menu/Main/Cadastros/cadastrosMenuUI.c.s

ui/Menu/Main/Status/statusMenuUI.o: ui/Menu/Main/Status/statusMenuUI.c.o

.PHONY : ui/Menu/Main/Status/statusMenuUI.o

# target to build an object file
ui/Menu/Main/Status/statusMenuUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Status/statusMenuUI.c.o
.PHONY : ui/Menu/Main/Status/statusMenuUI.c.o

ui/Menu/Main/Status/statusMenuUI.i: ui/Menu/Main/Status/statusMenuUI.c.i

.PHONY : ui/Menu/Main/Status/statusMenuUI.i

# target to preprocess a source file
ui/Menu/Main/Status/statusMenuUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Status/statusMenuUI.c.i
.PHONY : ui/Menu/Main/Status/statusMenuUI.c.i

ui/Menu/Main/Status/statusMenuUI.s: ui/Menu/Main/Status/statusMenuUI.c.s

.PHONY : ui/Menu/Main/Status/statusMenuUI.s

# target to generate assembly for a file
ui/Menu/Main/Status/statusMenuUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/Status/statusMenuUI.c.s
.PHONY : ui/Menu/Main/Status/statusMenuUI.c.s

ui/Menu/Main/mainMenuUI.o: ui/Menu/Main/mainMenuUI.c.o

.PHONY : ui/Menu/Main/mainMenuUI.o

# target to build an object file
ui/Menu/Main/mainMenuUI.c.o:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/mainMenuUI.c.o
.PHONY : ui/Menu/Main/mainMenuUI.c.o

ui/Menu/Main/mainMenuUI.i: ui/Menu/Main/mainMenuUI.c.i

.PHONY : ui/Menu/Main/mainMenuUI.i

# target to preprocess a source file
ui/Menu/Main/mainMenuUI.c.i:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/mainMenuUI.c.i
.PHONY : ui/Menu/Main/mainMenuUI.c.i

ui/Menu/Main/mainMenuUI.s: ui/Menu/Main/mainMenuUI.c.s

.PHONY : ui/Menu/Main/mainMenuUI.s

# target to generate assembly for a file
ui/Menu/Main/mainMenuUI.c.s:
	$(MAKE) -f CMakeFiles/AeroTracker.dir/build.make CMakeFiles/AeroTracker.dir/ui/Menu/Main/mainMenuUI.c.s
.PHONY : ui/Menu/Main/mainMenuUI.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... AeroTracker"
	@echo "... edit_cache"
	@echo "... core/Aeronave/Aeronave.o"
	@echo "... core/Aeronave/Aeronave.i"
	@echo "... core/Aeronave/Aeronave.s"
	@echo "... core/Aeronave/Comparator.o"
	@echo "... core/Aeronave/Comparator.i"
	@echo "... core/Aeronave/Comparator.s"
	@echo "... core/Aeroporto/Aeroporto.o"
	@echo "... core/Aeroporto/Aeroporto.i"
	@echo "... core/Aeroporto/Aeroporto.s"
	@echo "... core/Aeroporto/Comparator.o"
	@echo "... core/Aeroporto/Comparator.i"
	@echo "... core/Aeroporto/Comparator.s"
	@echo "... core/Cliente/Cliente.o"
	@echo "... core/Cliente/Cliente.i"
	@echo "... core/Cliente/Cliente.s"
	@echo "... core/Cliente/Comparator.o"
	@echo "... core/Cliente/Comparator.i"
	@echo "... core/Cliente/Comparator.s"
	@echo "... core/List/Operations/List.o"
	@echo "... core/List/Operations/List.i"
	@echo "... core/List/Operations/List.s"
	@echo "... core/List/Sort/mergeSort.o"
	@echo "... core/List/Sort/mergeSort.i"
	@echo "... core/List/Sort/mergeSort.s"
	@echo "... core/Voo/Comparator.o"
	@echo "... core/Voo/Comparator.i"
	@echo "... core/Voo/Comparator.s"
	@echo "... core/Voo/VooInfo.o"
	@echo "... core/Voo/VooInfo.i"
	@echo "... core/Voo/VooInfo.s"
	@echo "... input/string.o"
	@echo "... input/string.i"
	@echo "... input/string.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.o"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.i"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/Alterar/alterarAeronaveUI.s"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.o"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.i"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/Deletar/deletarAeronaveUI.s"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.o"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.i"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Consultar/consultarAeronaveUI.s"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.o"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.i"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/Inserir/inserirAeronaveUI.s"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.o"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.i"
	@echo "... ui/Menu/Main/Cadastros/Aeronave/cadastrosAeronaveUI.s"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.o"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.i"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/Alterar/alterarClienteUI.s"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.o"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.i"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/Deletar/deletarClienteUI.s"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.o"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.i"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Consultar/consultarClienteUI.s"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.o"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.i"
	@echo "... ui/Menu/Main/Cadastros/Cliente/Inserir/inserirClienteUI.s"
	@echo "... ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.o"
	@echo "... ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.i"
	@echo "... ui/Menu/Main/Cadastros/Cliente/cadastrosClienteUI.s"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.o"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.i"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/Alterar/alterarVooUI.s"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.o"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.i"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/Deletar/deletarVooUI.s"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.o"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.i"
	@echo "... ui/Menu/Main/Cadastros/Voo/Consultar/consultarVooUI.s"
	@echo "... ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.o"
	@echo "... ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.i"
	@echo "... ui/Menu/Main/Cadastros/Voo/Inserir/inserirVooUI.s"
	@echo "... ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.o"
	@echo "... ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.i"
	@echo "... ui/Menu/Main/Cadastros/Voo/cadastrosVooUI.s"
	@echo "... ui/Menu/Main/Cadastros/cadastrosMenuUI.o"
	@echo "... ui/Menu/Main/Cadastros/cadastrosMenuUI.i"
	@echo "... ui/Menu/Main/Cadastros/cadastrosMenuUI.s"
	@echo "... ui/Menu/Main/Status/statusMenuUI.o"
	@echo "... ui/Menu/Main/Status/statusMenuUI.i"
	@echo "... ui/Menu/Main/Status/statusMenuUI.s"
	@echo "... ui/Menu/Main/mainMenuUI.o"
	@echo "... ui/Menu/Main/mainMenuUI.i"
	@echo "... ui/Menu/Main/mainMenuUI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

